# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x06\x63onfig\x1a\x1fgoogle/protobuf/timestamp.proto\")\n\rConfigRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\"*\n\x0e\x43onfigResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t2M\n\rConfigService\x12<\n\tsetConfig\x12\x15.config.ConfigRequest\x1a\x16.config.ConfigResponse\"\x00\x42&\n\x13\x63om.licscrap.configB\x06\x43onfigP\x01\xa2\x02\x04\x43ONFb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.licscrap.configB\006ConfigP\001\242\002\004CONF'
  _globals['_CONFIGREQUEST']._serialized_start=57
  _globals['_CONFIGREQUEST']._serialized_end=98
  _globals['_CONFIGRESPONSE']._serialized_start=100
  _globals['_CONFIGRESPONSE']._serialized_end=142
  _globals['_CONFIGSERVICE']._serialized_start=144
  _globals['_CONFIGSERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
