# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: models.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'models.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmodels.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x02\n\x0bPublication\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x11\n\thierarchy\x18\x06 \x01(\t\x12,\n\x08pub_date\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x61rt_type\x18\x08 \x01(\t\x12\x0c\n\x04prob\x18\t \x01(\x02\x12\x17\n\x0f\x63ontent_fetched\x18\n \x01(\x08\x12.\n\ncreated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04mark\x18\x0c \x01(\x05\x12\x0e\n\x06status\x18\r \x01(\x05\x12,\n\x08\x64ue_date\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ndue_reason\x18\x0f \x01(\x05\x12\n\n\x02id\x18\x10 \x01(\x05\"D\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05\x32N\n\x0cModelService\x12>\n\x0fgetPublications\x12\x12.models.GetRequest\x1a\x13.models.Publication\"\x00\x30\x01\x42&\n\x13\x63om.licscrap.modelsB\x06ModelsP\x01\xa2\x02\x04MDLSb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'models_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.licscrap.modelsB\006ModelsP\001\242\002\004MDLS'
  _globals['_PUBLICATION']._serialized_start=58
  _globals['_PUBLICATION']._serialized_end=429
  _globals['_GETREQUEST']._serialized_start=431
  _globals['_GETREQUEST']._serialized_end=499
  _globals['_MODELSERVICE']._serialized_start=501
  _globals['_MODELSERVICE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
